### ISSUE TITLE
[BE] Migration to Timescale DB & single Assessments Table

### ISSUE THREAD

**Issue by choxx** [Mission-Prerna/nl-apis#53]
Extension of the existing PoC ticket: https://github.com/Mission-Prerna/benchmarking-suite/issues/5

**Comment by choxx** [comment]
- [ ] 1. 26th EOD - Setup DB migration on Timescale DB + single table for assessments @singhalkarun 
- [ ] 2. 27th + 28th EOD - Code changes (@choxx ) + continuous aggregates (@singhalkarun )
- [ ] 3. 29th - Testing + bug fixes (@AakashSatpute119 @Nirali010129 @aakashyadav-kgp )
- [ ] 4. 30/1/2 - Actual Migration (@choxx @singhalkarun )
- [ ] 5. Continuous Aggregates: refresh policy to be checked & define the best possibility. @singhalkarun 
- [ ] 6. **In Students flow,** Continuous Aggregates to be added as v2 apis & flag on firebase to switch to v1 if needed to rollback (response format has to be same on both versions). @choxx @ujjwalsaxena03

**Comment by choxx** [comment]
In migration, we are planning majorly:-
1. Make single table structure for assessments using Hypertable on Timescale DB
2. Use continuos aggregates for metrics

With Teacher<>students flow in phase 1+2, below are the constraints, because:
- Firebase Flag based support for continuos aggregates cannot be done with current live app
- Metrics API code changes to be made won't be compatible with Students flow development
- Assessment API code changes to be made won't be compatible with Students flow development
- Materialized views migration now + later with new flow
- Technosys APIs syncing mechanism (low impact though)

**Comment by aakashyadav-kgp** [comment]
@karntrehan we need to discuss this once  before moving ahead.

**Comment by choxx** [comment]
## Final plan
Migration would be 2 phases on prod.

### Phase 1
1. Migrate to Timescale DB & create a single Assessments Hypertable along with continuous aggregates.
2. Start recording submissions in the old quarter table + Hypertable
All the existing Metrics APIs & MV including technosys GET assessment APIs will continue to work as usual.

### Phase 2
One week later, we'll compare continuous aggregates with the old metrics APIs & performance; if the stats are matching & performance is promising, we can then plan to:
1. Switch the metrics APIs to continuous aggregates
2. Fix MV queries to use single assessments table
3. Patch GET assessment APIs to use single hypertable
4. Completely obsolete the quarter tables flow

**Comment by choxx** [comment]
point 1) DB dump is still in progress; last dump failed because some tables weren't copied.
Point 2) in progress today.

We will be going ahead with Migration on coming plan as it won't impact prod users by any means (post closure of Friday testing & go ahead by QAs).

**Comment by choxx** [comment]
Run some aggregate queries for 1 month data & verify if they match for older vs new table and ensure the data from hypertable is being picked from only 1 partition.

**Comment by choxx** [comment]
- DB dump finished
- Code changes done for dumping assessment records in quarter tables + hypertable.
- Awaiting a testing build (from @ujjwalsaxena03) for QAs testing

**Comment by AakashSatpute119** [comment]
Build : https://drive.google.com/file/d/1s7TBjejh7UODX4p5PLw6uC5nJaHBXYqx/view?usp=sharing tested with all actors, assessments are submitted in new single **assessment** table as well as in old monthly table **assessment_visit_results_v2_2023_jul_sep**  .  @karntrehan

**Comment by choxx** [comment]
## Pre Migration

- [ ] 1. Stop backend APIs
- [ ] 2. Stop User Service
- [ ] 3. Stop Fusion Auth
- [ ] 4. Stop Hasura
- [ ] 5. Block public access to DB container
- [ ] 6. Create backup of Postgres Data https://gist.github.com/choxx/30fb7f7a5b780c75ba48f24119b188dd?permalink_comment_id=4705981#gistcomment-4705981

## During Migration

- [ ] 1. Setup Gatekeeper for system upgrades
- [ ] 2. Setup timescale db container https://gist.github.com/choxx/30fb7f7a5b780c75ba48f24119b188dd#file-docker-compose-yml
- [ ] 3. Post setup, increase worker memory & shared buffers and restart the container
- [ ] 4. Setup temp Hasura & run migrations using Hasura
- [ ] 5. Restore Data into timescaledb
- [ ] 6. Migrate data from old tables to single `assessments` table https://gist.github.com/choxx/30fb7f7a5b780c75ba48f24119b188dd#file-migrate-sql
- [ ] 7. Validate everything & start services

**Comment by charanpreet-s** [comment]
Phase 1 of implementation is done. Continuos aggregate to be done after one week post-checking data sanity.

**Comment by aakashyadav-kgp** [comment]
Rollback to be implemented on BE system only.

**Comment by choxx** [comment]
Closing this ticket as the leftovers have been moved to be picked in phase 3 #61
